### ISSUE TITLE
postgres service deploy failed

### ISSUE THREAD

**Issue by terovirtanen** [andersinno/kolga-deploy-service-action#1]
postgres service deploy failed because missing bitnami/postgresql chart

` Upgrading chart from 'bitnami/postgresql': Error: failed to download "bitnami/postgresql" at version "7.7.2"`

review step
```
      - name: Review-Services
        uses: andersinno/kolga-deploy-service-action@v2
        with:
          projects: PALVELUTARJOTIN
        env:
          POSTGRES_IMAGE: "docker.io/andersinnovations/postgis:11-bitnami"
```

link to failed service deploy
https://github.com/City-of-Helsinki/palvelutarjotin/runs/6861255051?check_suite_focus=true
